
## Introduction

- the data is in '/data/manke/processing/balan/Yilong_SG_data/run_2218/reproducible/2_qc/3_RSeQC/s*.tab'
- plot all the numbers from the RSeQC 'read_distribution.py' command (.png in /data/manke/processing/balan/Yilong_SG_data/run_2218/reproducible/2_qc/)


```{r, load data}
## get all file names
path_dir="/data/manke/processing/balan/Yilong_SG_data/run_2218/reproducible/2_qc/3_RSeQC"

l.files <- list.files(path = path_dir, pattern = "*.tab", all.files = FALSE,
           full.names = TRUE, recursive = FALSE,                                    # full.names = TRUE
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

# to sort the files in numerical order
library(gtools)
l.files <- mixedsort(sort(l.files))

# load all files and bind them in one data frame
df.all_data <- do.call(rbind, (lapply(l.files, function(x)read.table(x, skip = 5, stringsAsFactors = FALSE, nrows=10, fill=TRUE, header=FALSE)[c(1,3)])))

# name the dataframe
colnames(df.all_data) <- colnames(read.table(l.files[1], skip = 4, stringsAsFactors = FALSE, nrows=10, fill=TRUE, header=TRUE)[c(1,3)])

#Insert columns with experimental condition and replicate number
l.cond <- rep(paste0('s',1:27), each=10)
l.repl <- rep(1:3, each=10)
l.expCond  <- rep(c('totRNA_mock', 'totRNA_arsenite', 'totRNA_HS', 'totRNA_NaCl', 'totRNA_UV', 'sgRNA_arsenite', 'sgRNA_HS', 'sgRNA_NaCl', 'sgRNA_UV'), each=30)
  
df.all_complete <- transform(df.all_data,
                             Sample = l.cond,
                             Replicate = l.repl,
                             ExpCond = l.expCond)
```

```{r, plot}
## make the plot
library(ggplot2)

ggplot(data=df.all_complete,
       aes(x=Sample, y=Tag_count, fill = factor(Group) ) ) +
    geom_bar(stat="identity", position = "fill") +
    #theme_bw(base_size = 14) +
    theme(legend.position="bottom") +
    coord_flip() +
    ylab("Tags per kb") +  ggtitle("Tags per kb > 10") + xlab("") +
    #+ scale_fill_manual(values = c("forestgreen","darkseagreen","green","limegreen") )
    scale_fill_manual(values = c("#7cb5ec", "#434348", "#90ed7d", "#f7a35c", "#8085e9", "#f15c80", "#e4d354", "#2b908f", "#f45b5b", "#91e8e1") )
```

```{r, plot_rearr}
## make the plot
library(ggplot2)

# lock in the name of the samples and reorder levels in factor:
df.all_complete$Sample <- factor(df.all_complete$Sample, levels=paste0('s',27:1))
df.all_complete$Group <- factor(df.all_complete$Group, levels=as.character(df.all_complete$Group[10:1]))
df.all_complete$ExpCond <- factor(df.all_complete$ExpCond, levels = unique(l.expCond))

path_image='/data/manke/processing/balan/Yilong_SG_data/run_2218/reproducible/2_qc'
png(paste0(path_image,"/2218_3_RSeQC_readDistribution_fig2e_col4.png"),
  width = 8*300,        # 5 x 300 pixels
  height = 5*300,
  res = 300,            # 300 pixels per inch
  pointsize = 8)        # smaller font size

ggplot(data=df.all_complete,
  aes(x=Sample, y=Tag_count, fill = factor(Group) ) ) +
  geom_bar(stat="identity", position = "fill") +
  coord_flip() +
  theme_classic(base_size = 10) +
  facet_wrap(vars(ExpCond), nrow = 9, ncol = 1, scales = "free_y", strip.position = "right") +
  # axes
  theme(axis.line.y = element_blank(), axis.line.x = element_blank(),     
        axis.title.y = element_text(vjust = +3),
        axis.title.x = element_text(vjust = +0.2)) +
  xlab("Sample") +  ylab("Feature") +  
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  
  # title  
  ggtitle("Distribution of reads per features") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  # legend
  theme(legend.position="bottom", legend.title = element_blank(), 
        legend.margin = margin(0, 0, 4, 0), legend.box.margin = margin(-10, 0, 0, 0),
        legend.spacing.y = unit(2.0, 'cm'), legend.text  = element_text(size = 8)) +
  guides(guide_legend(title.vjust = 2)) +

  # the legend on the left = strip
  theme(panel.spacing = unit(0.4, "lines"), strip.background = element_rect(colour="white"),
        strip.text.y = element_text(size = 8, colour = "black", face = "bold",
                                    angle = 0,  
                                    hjust = 0, margin = margin(2, 2, 2, 2, "pt")) ) +
  
  # color categories  
  scale_fill_manual(values = c("#7cb5ec", "#434348", "#90ed7d", "#f7a35c", "#8085e9", "#f15c80", "#e4d354", "#2b908f", "#f45b5b", "#91e8e1"), limits = rev(levels(df.all_complete$Group)) )

dev.off()
```
