
## Introduction

- the data is in '/output/3_qc_kraken_RSeQC/s*.rep'

- plot only the numbers referring to human RNA: genomic, mitochondrial and ribosomal (.png in /output/3_qc_kraken_RSeQC/)

```{r, load_libraries}
suppressPackageStartupMessages(library(gtools))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(ggplot2))
```


```{r, load data}
## get all file names
path_dir="../output/3_qc_kraken_RSeQC/1_kraken"

l.files <- list.files(path = path_dir, pattern = "*.rep", all.files = FALSE,
           full.names = TRUE, recursive = FALSE,                              
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

# to sort the files in numerical order
l.files <- mixedsort(sort(l.files))

# load all files, together with the file basename and no extension
# bind the loaded files in one data frame
df.all_data <- do.call(rbind, (lapply(l.files, 
                      function(x) read.table(x, stringsAsFactors = FALSE, fill=TRUE, header=FALSE)[c(1,4,6)] %>% 
                      mutate(Sample = basename(sub('\\.rep$', '', x) ) ) ) ) ) 

# name the dataframe
colnames(df.all_data) <- c("Percentage", "Attribute", "Class", "Sample")

# keep only the rowns for which 4th column is 'S' 
df.all_data <- df.all_data[df.all_data$Attribute == 'S',]

# delete 'Attribute' column
df.all_data$Attribute <- NULL
####################

#Insert columns with experimental condition and replicate number
l.cond <- rep(paste0('s',1:27))
l.expCond  <- rep(c('totRNA_mock', 'totRNA_arsenite', 'totRNA_HS', 'totRNA_NaCl', 'totRNA_UV', 
                    'sgRNA_arsenite', 'sgRNA_HS', 'sgRNA_NaCl', 'sgRNA_UV'), each=3)

# add the ExpCond column
for (j in 1:length(unique(df.all_data$Sample) ) ) {
  df.all_data$ExpCond[df.all_data$Sample == unique(df.all_data$Sample)[j] ] <- l.expCond[j]  
  }

# add the Replicate column
v.samp <- df.all_data$Sample
for (j in 1:length(unique(v.samp) ) ) {
  #get only the number portion from the name of the sample (e.g. 19 from s19)
  clean_rep <- as.numeric(gsub('\\D','', unique(v.samp)[j]) )
  #attribute the replicate number (1 to 3) to the samples
  df.all_data$Replicate[v.samp == unique(v.samp)[j] ] <- ifelse(clean_rep %% 3 == 0, 3, 
                                                         ifelse(clean_rep %% 3 == 1, 1, 2) )
}

head(df.all_data)
```

```{r, retain_top5}
# reorder percentages decreasingly, within each sample
df.reorder <- df.all_data[with(df.all_data, order(Sample, -Percentage) ),]
head(df.reorder)
```



```{r, recalculate_classes, warning=FALSE, message=FALSE, tidy=TRUE}
# sum up the 3 human categories, then subtract them from 100%, and call all of that 'Other' class

l.calcPerOther <- df.reorder %>% 
  filter(str_detect(Class, "human")) %>% 
  group_by(Sample) %>% 
  summarise(Percentage=sum(Percentage)) %>% 
  mutate(Percentage=100-Percentage) %>% 
  pull(Percentage)

df.other <- df.reorder %>% filter(str_detect(Class, "human")) %>% 
  group_by(Sample,ExpCond,Replicate) %>% 
  summarise(last(Percentage)) %>% 
  ungroup() %>% 
  mutate(Class="Other", Percentage=l.calcPerOther) %>% 
  dplyr::select(Percentage,Class,Sample,ExpCond,Replicate) %>% 
  bind_rows(df.reorder %>% filter(str_detect(Class, "human")) %>% 
  group_by(Sample), .) %>% 
  arrange(Sample) 

head(df.other)
```

```{r, replot}
## make the plot
# lock in the name of the samples and reorder levels in factor:
df.other$Sample <- factor(df.other$Sample, levels=paste0('s',27:1))
df.other$Class <- factor(df.other$Class, levels=as.character(rev(unique(df.other$Class)) ) )
df.other$ExpCond <- factor(df.other$ExpCond, levels = unique(l.expCond))

path_image='../images/'
# png(paste0(path_image,"/figS3g_kraken_contamination_changePerc.png"),
#   width = 8*300,        # 5 x 300 pixels
#   height = 5*300,
#   res = 300,            # 300 pixels per inch
#   pointsize = 8)        # smaller font size

ggplot(data=df.other,
  aes(x=Percentage, 
      y=Sample, 
      fill = factor(Class) ) ) +
  geom_bar(stat="identity", position = "fill") +
  theme_classic(base_size = 10) +
  facet_wrap(vars(ExpCond), 
             nrow = 9, 
             ncol = 1, 
             scales = "free_y", 
             strip.position = "right") +
  # axes
  theme(axis.line.y = element_blank(), 
        axis.line.x = element_blank(),     
        axis.title.y = element_text(vjust = +3),
        axis.title.x = element_text(vjust = +0.2),
        axis.ticks.x = 
        ) +
  xlab("Percentage read contamination") +  
  ylab("Sample") +  
  scale_x_continuous(expand = c(0, 0), 
                     labels=scales::percent_format()  ) +
  # title  
  ggtitle("Contamination of reads") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  # legend
  theme(legend.position="right", 
        legend.title = element_blank(),
        legend.margin = margin(0, 0, 4, 0), 
        legend.box.margin = margin(-10, 0, 0, 0),
        legend.spacing.y = unit(2.0, 'cm'), 
        legend.text  = element_text(size = 10)) +
  guides(guide_legend(title.vjust = 2)) +
  # the legend on the right = strip
  theme(panel.spacing = unit(0.4, "lines"), 
        strip.background = element_rect(colour="white"),
        strip.text.y = element_text(size = 8, 
                                    colour = "black", 
                                    face = "bold",
                                    angle = 0,
                                    hjust = 0, 
                                    margin = margin(2, 2, 2, 2, "pt")) ) +
  # color categories  
  scale_fill_manual(values = c("#7cb5ec", "#434348", "#90ed7d", "grey"), 
                    limits = rev(levels(df.other$Class)) )

#dev.off()
```