paths:
    main_dir: /data/manke/group/balan/projects/Yilong_SG_Illumina_totRNAhu
    
    # references:
    gtf_v27: /data_int/references/GRCh38_v27_genes.gtf
    bed_v27: /data_int/references/GRCh38_v27_genes.bed
    genome_GRCh38: /data_int/references/GRCh38_genome.fa
    slop_p10_GRCh38: /data_int/references/GRCh38_v27_genes_slop_p10.bed
 
    bam_files: /data_int/bam
    fastq_files: /data_int/fastq 

    # output folders for the mRNA-seq snakePipes
    1a_mRNA-seq: /output/test_mRNA
    1b_mRNA-seq: /output/1b_mRNAseq_alignment_splitSampleSheets
    1c_mRNA-seq: /output/1c_mRNAseq_tx_1SampleSheet
    1d_mRNA-seq: /output/1d_mRNAseq_tx_splitSampleSheets

    # the sample sheet for totalRNA samples and split sample sheets for sgRNA 
    totRNA_smplSheet: /data_int/sampleSheets/batch_totalRNA_corrected_sampleSheet.tsv
    sgRNA_split_smplSheet_dir: /data_int/sampleSheets/sampleSheets_sgRNA_split

    # output folder for fastq QC (RSeQC and kraken)
    3_qc_kraken: /output/3_qc_kraken_RSeQC/1_kraken
    3_qc_kraken_multiQC: /output/3qc_kraken_RSeQC/2_kraken_multiQC
    kraken_db: /data_int/kraken2_contaminome/contaminomedb
    3_qc_RSeQC: /output/3_qc_kraken_RSeQC/3_RSeQC
    3_qc_RSeQC_multiQC: /output/3_qc_kraken_RSeQC/4_RSeQC_multiQC

    # sources for HaplotypeCaller
    5_bamSplit: /output/5_SNP_TtoCmut/1_bam_split
    5_bamSplit_RG: /output/5_SNP_TtoCmut/2_bam_addRG
    5_merged: /output/5_SNP_TtoCmut/3_bam_RG_merge
    5_SplitNCigar: /output/5_SNP_TtoCmut/4_bam_SplitNCigar
    5_SplitNCigar_logs: /output/5_SNP_TtoCmut/4_bam_SplitNCigar/logs

    5_HC_norm: /output/5_SNP_TtoCmut/5_HaplotypeCaller_norm
    5_HC_norm_logs: /output/5_SNP_TtoCmut/5_HaplotypeCaller_norm/logs
    5_HC_norm_bamOut: /output/5_SNP_TtoCmut/5_HaplotypeCaller_norm/bamOut

    5_HC_ERC: /output/5_SNP_TtoCmut/5_HaplotypeCaller_ERC
    5_HC_ERC_logs: /output/5_SNP_TtoCmut/5_HaplotypeCaller_ERC/logs
    5_HC_ERC_bamOut: /output/5_SNP_TtoCmut/5_HaplotypeCaller_ERC/bamOut
    
    5_HCnorm_softFilt_all: /output/5_SNP_TtoCmut/6_HCnorm_SNV/1_HCnorm_softFilt_all
    5_HCnorm_softFilt_logs: /output/5_SNP_TtoCmut/6_HCnorm_SNV/1_HCnorm_softFilt_all/logs
    5_HCnorm_hardFilt_SNV: /output/5_SNP_TtoCmut/6_HCnorm_SNV/2_HCnorm_hardFilt_SNV
    5_HCnorm_hardFilt_logs: /output/5_SNP_TtoCmut/6_HCnorm_SNV/2_HCnorm_hardFilt_SNV/logs

    5_HC_ERC_DBs: /output/5_SNP_TtoCmut/6_HC_ERC_SNV/1_HC_ERC_DBs
    5_HC_ERC_DBs_logs: /output/5_SNP_TtoCmut/6_HC_ERC_SNV/1_HC_ERC_DBs/logs
    5_HC_ERC_vcfs: /output/5_SNP_TtoCmut/6_HC_ERC_SNV/2_HC_ERCvcfs
    5_HC_ERC_vcfs_logs: /output/5_SNP_TtoCmut/6_HC_ERC_SNV/2_HC_ERCvcfs/logs


    5_HC_ERC_hardFilt_SNV: /output/5_SNP_TtoCmut/6_HC_ERC_SNV/2_HCnorm_hardFilt_SNV
    5_HC_ERC_hardFilt_logs: /output/5_SNP_TtoCmut/6_HC_ERC_SNV/2_HCnorm_hardFilt_SNV/logs
