paths:
    main_dir: /data/manke/group/balan/projects/Yilong_SG_Illumina_totRNAhu
    
    # references:
    gtf_v27: /data_int/references/GRCh38_v27_genes.gtf
    bed_v27: /data_int/references/GRCh38_v27_genes.bed
 
    bam_files: /data_int/bam
    fastq_files: /data_int/fastq 

    # output folders for the mRNA-seq snakePipes
    1a_mRNA-seq: /output/test_mRNA
    1b_mRNA-seq: /output/1b_mRNAseq_alignment_splitSampleSheets
    1c_mRNA-seq: /output/1c_mRNAseq_tx_1SampleSheet
    1d_mRNA-seq: /output/1d_mRNAseq_tx_splitSampleSheets

    # the sample sheet for totalRNA samples and split sample sheets for sgRNA 
    totRNA_smplSheet: /data_int/sampleSheets/batch_totalRNA_corrected_sampleSheet.tsv
    sgRNA_split_smplSheet_dir: /data_int/sampleSheets/sampleSheets_sgRNA_split

    # output folder for fastq QC (RSeQC and kraken)
    3_qc_kraken: /output/3_qc_kraken_RSeQC/1_kraken
    3_qc_kraken_multiQC: /output/3qc_kraken_RSeQC/2_kraken_multiQC
    kraken_db: /data_int/kraken2_contaminome/contaminomedb
    3_qc_RSeQC: /output/3_qc_kraken_RSeQC/3_RSeQC
    3_qc_RSeQC_multiQC: /output/3_qc_kraken_RSeQC/4_RSeQC_multiQC

    # sources for HaplotypeCaller
    5_SNP_bamSplit: /output/5_SNP_TtoCmut/1_bam_split
