paths:
    main_dir: /data/manke/group/balan/projects/Yilong_SG_Illumina_totRNAhu
    
    # references:
    gtf_v27: /data_int/references/GRCh38_v27_genes.gtf
    bed_v27: /data_int/references/GRCh38_v27_genes.bed
    genome_GRCh38: /data_int/references/GRCh38_genome.fa
    slop_p10_GRCh38: /data_int/references/GRCh38_v27_genes_slop_p10.bed
    genome_GRCh38.fai: /data_int/references/GRCh38_genome.fa.fai

    # initial folders    
    bam_files: /data_int/bam
    fastq_files: /data_int/fastq 


    # external software
    ARTDeco: ext_software/ARTDeco

    # output folders for the mRNA-seq snakePipes
    1a_mRNA-seq: /output/test_mRNA
    1b_mRNA-seq: /output/1b_mRNAseq_alignment_splitSampleSheets
    1c_mRNA-seq: /output/1c_mRNAseq_tx_1SampleSheet
    1d_mRNA-seq: /output/1d_mRNAseq_tx_splitSampleSheets

    # the sample sheet for totalRNA samples and split sample sheets for sgRNA 
    totRNA_smplSheet: /data_int/sampleSheets/batch_totalRNA_corrected_sampleSheet.tsv
    sgRNA_split_smplSheet_dir: /data_int/sampleSheets/sampleSheets_sgRNA_split
    totRNA_smplSheet_ARTDeco: /data_int/sampleSheets/batch_totalRNA_corrected_sampleSheet_ARTDeco.tsv
    sgRNA_smplSheet_ARTDeco: /data_int/sampleSheets/batch_sgRNA_corrected_sampleSheet_ARTDeco.tsv
    totRNA_compSheet_ARTDeco: /data_int/sampleSheets/batch_totalRNA_corrected_compSheet_ARTDeco.tsv
    sgRNA_compSheet_ARTDeco: /data_int/sampleSheets/batch_sgRNA_corrected_compSheet_ARTDeco.tsv

    # output folder for fastq QC (RSeQC and kraken)
    3_qc_kraken: /output/3_qc_kraken_RSeQC/1_kraken
    3_qc_kraken_multiQC: /output/3qc_kraken_RSeQC/2_kraken_multiQC
    kraken_db: /data_int/kraken2_contaminome/contaminomedb
    3_qc_RSeQC: /output/3_qc_kraken_RSeQC/3_RSeQC
    3_qc_RSeQC_multiQC: /output/3_qc_kraken_RSeQC/4_RSeQC_multiQC

    # sources for HaplotypeCaller
    5_bamSplit: /output/5_SNP_TtoCmut/1_bam_split
    5_bamSplit_RG: /output/5_SNP_TtoCmut/2_bam_addRG
    5_merged: /output/5_SNP_TtoCmut/3_bam_RG_merge
    5_SplitNCigar: /output/5_SNP_TtoCmut/4_bam_SplitNCigar
    5_SplitNCigar_logs: /output/5_SNP_TtoCmut/4_bam_SplitNCigar/logs

    5_HC_ERC: /output/5_SNP_TtoCmut/5_HaplotypeCaller_ERC
    5_HC_ERC_logs: /output/5_SNP_TtoCmut/5_HaplotypeCaller_ERC/logs
    5_HC_ERC_bamOut: /output/5_SNP_TtoCmut/5_HaplotypeCaller_ERC/bamOut
   
    5_HC_SNP: /output/5_SNP_TtoCmut/6_SNP/1_SNP_Genotype_vcfs
    5_HC_SNP_log: /output/5_SNP_TtoCmut/6_SNP/1_SNP_Genotype_vcfs/logs
    5_HC_SNP_filt: /output/5_SNP_TtoCmut/6_SNP/2_SNP_filter
    5_HC_SNP_filtLog: /output/5_SNP_TtoCmut/6_SNP/2_SNP_filter/logs

    5_HC_all: /output/5_SNP_TtoCmut/6_SNP/1_all_Genotype_vcfs
    5_HC_all_log: /output/5_SNP_TtoCmut/6_SNP/1_all_Genotype_vcfs/logs
    5_HC_all_filt: /output/5_SNP_TtoCmut/6_SNP/2_all_filter
    5_HC_all_filtLog: /output/5_SNP_TtoCmut/6_SNP/2_all_filter/logs

    5_SNPsites: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/1_sites
    5_SNPsitesLog: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/1_sites/logs
    5_SNPmerge: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/2_merged
    5_SNPmergeLog: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/2_merged/logs
    5_SNPeq3: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/3_eq3
    5_SNPeq3Log: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/3_eq3/logs
    5_counts: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/4_counts
    4_countsLog: /output/5_SNP_TtoCmut/6_SNP/3_SNP_processedMut/4_counts/logs


    # sources for ARTDeco
    9_artdeco: /output/9_ARTDeco
