#!/bin/sh
# properties = {"type": "single", "rule": "DeeptoolsMultiBamSummaryDuplicates", "local": false, "input": ["RawData/03aMappingSTARRscript/DHX9_WT_rep1.bam", "RawData/03bMappingSTARPython/DHX9_WT_rep1.bam", "RawData/03aMappingSTARRscript/DHX9_WT_rep2.bam", "RawData/03bMappingSTARPython/DHX9_WT_rep2.bam", "RawData/03aMappingSTARRscript/DHX9_WT_rep3.bam", "RawData/03bMappingSTARPython/DHX9_WT_rep3.bam", "RawData/03aMappingSTARRscript/DHX9_UV_rep1.bam", "RawData/03bMappingSTARPython/DHX9_UV_rep1.bam", "RawData/03aMappingSTARRscript/DHX9_UV_rep2.bam", "RawData/03bMappingSTARPython/DHX9_UV_rep2.bam", "RawData/03aMappingSTARRscript/DHX9_UV_rep3.bam", "RawData/03bMappingSTARPython/DHX9_UV_rep3.bam", "RawData/03aMappingSTARRscript/DHX9_WT_rep1.bam.bai", "RawData/03bMappingSTARPython/DHX9_WT_rep1.bam.bai", "RawData/03aMappingSTARRscript/DHX9_WT_rep2.bam.bai", "RawData/03bMappingSTARPython/DHX9_WT_rep2.bam.bai", "RawData/03aMappingSTARRscript/DHX9_WT_rep3.bam.bai", "RawData/03bMappingSTARPython/DHX9_WT_rep3.bam.bai", "RawData/03aMappingSTARRscript/DHX9_UV_rep1.bam.bai", "RawData/03bMappingSTARPython/DHX9_UV_rep1.bam.bai", "RawData/03aMappingSTARRscript/DHX9_UV_rep2.bam.bai", "RawData/03bMappingSTARPython/DHX9_UV_rep2.bam.bai", "RawData/03aMappingSTARRscript/DHX9_UV_rep3.bam.bai", "RawData/03bMappingSTARPython/DHX9_UV_rep3.bam.bai"], "output": ["Output/04aDeeptoolsSTARDuplicates/multiBamSummary.read.coverage.bins.npz"], "wildcards": {}, "params": {"labels": ["Rscript/DHX9_WT_rep1", "Python/DHX9_WT_rep1", "Rscript/DHX9_WT_rep2", "Python/DHX9_WT_rep2", "Rscript/DHX9_WT_rep3", "Python/DHX9_WT_rep3", "Rscript/DHX9_UV_rep1", "Python/DHX9_UV_rep1", "Rscript/DHX9_UV_rep2", "Python/DHX9_UV_rep2", "Rscript/DHX9_UV_rep3", "Python/DHX9_UV_rep3"], "blacklist": "--blackListFileName /data/repository/organisms/GRCh38_ensembl/akundaje/blacklist.UseMe.bed", "read_extension": "--extendReads"}, "log": ["Output/04aDeeptoolsSTARDuplicates/logs/MultiBamSummary.out", "Output/04aDeeptoolsSTARDuplicates/logs/MultiBamSummary.err"], "threads": 50, "resources": {}, "jobid": 80, "cluster": {"memory": "6G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs && \
/data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/bin/python3.7 \
-m snakemake Output/04aDeeptoolsSTARDuplicates/multiBamSummary.read.coverage.bins.npz --snakefile /home/suny/scripts/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.jao73_0x RawData/03aMappingSTARRscript/DHX9_WT_rep1.bam RawData/03bMappingSTARPython/DHX9_WT_rep1.bam RawData/03aMappingSTARRscript/DHX9_WT_rep2.bam RawData/03bMappingSTARPython/DHX9_WT_rep2.bam RawData/03aMappingSTARRscript/DHX9_WT_rep3.bam RawData/03bMappingSTARPython/DHX9_WT_rep3.bam RawData/03aMappingSTARRscript/DHX9_UV_rep1.bam RawData/03bMappingSTARPython/DHX9_UV_rep1.bam RawData/03aMappingSTARRscript/DHX9_UV_rep2.bam RawData/03bMappingSTARPython/DHX9_UV_rep2.bam RawData/03aMappingSTARRscript/DHX9_UV_rep3.bam RawData/03bMappingSTARPython/DHX9_UV_rep3.bam RawData/03aMappingSTARRscript/DHX9_WT_rep1.bam.bai RawData/03bMappingSTARPython/DHX9_WT_rep1.bam.bai RawData/03aMappingSTARRscript/DHX9_WT_rep2.bam.bai RawData/03bMappingSTARPython/DHX9_WT_rep2.bam.bai RawData/03aMappingSTARRscript/DHX9_WT_rep3.bam.bai RawData/03bMappingSTARPython/DHX9_WT_rep3.bam.bai RawData/03aMappingSTARRscript/DHX9_UV_rep1.bam.bai RawData/03bMappingSTARPython/DHX9_UV_rep1.bam.bai RawData/03aMappingSTARRscript/DHX9_UV_rep2.bam.bai RawData/03bMappingSTARPython/DHX9_UV_rep2.bam.bai RawData/03aMappingSTARRscript/DHX9_UV_rep3.bam.bai RawData/03bMappingSTARPython/DHX9_UV_rep3.bam.bai /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/f1b063b6 --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/FLASH-seq.config.yaml  --allowed-rules DeeptoolsMultiBamSummaryDuplicates --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-conda  --conda-prefix /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.jao73_0x/80.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.jao73_0x/80.jobfailed"; exit 1)

