#!/bin/sh
# properties = {"type": "single", "rule": "PeaksCallingTSSRscript", "local": false, "input": ["ProcessedData/01aRemoveDuplicatesSTARRscript/CSobject.Rdata", "ProcessedData/AnnotationObjects/database.version.annotation.merge.transcript.region.gtf"], "output": ["ProcessedData/03aPeakCallingSTARTSSRscript/CSobject.Rdata", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_merged.bed", "Output/02aReadStatisticsSTARRscript/total.read.statistics.txt"], "wildcards": {}, "params": {"sampleinfo": "/data/processing3/akhtargroup/sunyd/Projects/FastqZhou2019FlashHumanDHXuv/sampleInfo.tsv", "output_dir": "ProcessedData/03aPeakCallingSTARTSSRscript/", "fold_change": "2.5", "window_size": 25, "prefix": "tss_foldch_2.5", "chr_file": "ProcessedData/BasicObjects/species.chrs.RData", "group": "/data/processing3/akhtargroup/sunyd/Projects/FastqZhou2019FlashHumanDHXuv/sampleInfo.tsv", "rscript": "/home/suny/scripts/snakeRNAPipes/shared/tools/Mapcap.tss.detection.R"}, "log": ["ProcessedData/03aPeakCallingSTARTSSRscript/tss.log"], "threads": 10, "resources": {}, "jobid": 108, "cluster": {"memory": "24G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs && \
/data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/bin/python3.7 \
-m snakemake ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed --snakefile /home/suny/scripts/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.ewapzbb0 ProcessedData/01aRemoveDuplicatesSTARRscript/CSobject.Rdata ProcessedData/AnnotationObjects/database.version.annotation.merge.transcript.region.gtf /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/e124a57d --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/FLASH-seq.config.yaml  --allowed-rules PeaksCallingTSSRscript --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-conda  --conda-prefix /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.ewapzbb0/108.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.ewapzbb0/108.jobfailed"; exit 1)

