#!/bin/sh
# properties = {"type": "single", "rule": "PeaksAnnotationPureclipRscript", "local": false, "input": ["ProcessedData/03aPeakCallingSTARPureclipRscript/DHX9_WT/peaks.bed", "ProcessedData/03aPeakCallingSTARPureclipRscript/DHX9_UV/peaks.bed", "ProcessedData/AnnotationObjects/species.database.constitutive.exons.gtf", "ProcessedData/AnnotationObjects/species.database.constitutive.introns.gtf"], "output": ["Output/05aPeakAnnotationSTARPureclipRscript/peaks.annotation.txt"], "wildcards": {}, "params": {"peakdir": "03aPeakCallingSTARPureclipRscript", "rscript": "/home/suny/scripts/snakeRNAPipes/shared/tools/FLASH.peak.annotation.R", "CalculationUnit": "/home/suny/scripts/snakeRNAPipes/shared/CalculationUnit", "alu": "/data/akhtar/suny/Genome/RepeatMasker/hg38.repeatmasker.alu.ensembl.bed", "alunot": "/data/akhtar/suny/Genome/RepeatMasker/hg38.repeatmasker.alu.not.ensembl.bed", "currentdir": "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto"}, "log": ["Output/05aPeakAnnotationSTARPureclipRscript/logs/peak.annotation.log"], "threads": 20, "resources": {}, "jobid": 115, "cluster": {"memory": "6G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto && \
/data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/bin/python3.7 \
-m snakemake Output/05aPeakAnnotationSTARPureclipRscript/peaks.annotation.txt --snakefile /home/suny/scripts/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/.snakemake/tmp.qt28ed8z ProcessedData/03aPeakCallingSTARPureclipRscript/DHX9_WT/peaks.bed ProcessedData/03aPeakCallingSTARPureclipRscript/DHX9_UV/peaks.bed ProcessedData/AnnotationObjects/species.database.constitutive.exons.gtf ProcessedData/AnnotationObjects/species.database.constitutive.introns.gtf /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/eeac4364 --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/FLASH-seq.config.yaml  --allowed-rules PeaksAnnotationPureclipRscript --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-conda  --conda-prefix /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/.snakemake/tmp.qt28ed8z/115.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/.snakemake/tmp.qt28ed8z/115.jobfailed"; exit 1)

