#!/bin/sh
# properties = {"log": ["RawData/02bSplittingPython/Logs/demultiplex.python.log"], "params": {"barcode": ["RawData/02bSplittingPython/DHX9_WT_rep1_sample_barcode.fastq", "RawData/02bSplittingPython/DHX9_WT_rep2_sample_barcode.fastq", "RawData/02bSplittingPython/DHX9_WT_rep3_sample_barcode.fastq", "RawData/02bSplittingPython/DHX9_UV_rep1_sample_barcode.fastq", "RawData/02bSplittingPython/DHX9_UV_rep2_sample_barcode.fastq", "RawData/02bSplittingPython/DHX9_UV_rep3_sample_barcode.fastq"], "sampleinfofa": "/data/processing3/akhtargroup/sunyd/Projects/FastqZhou2019FlashHumanDHXuv/barcode.fa", "tmp1": ["RawData/02bSplittingPython/DHX9_WT_rep1_R2_tmp.fastq", "RawData/02bSplittingPython/DHX9_WT_rep2_R2_tmp.fastq", "RawData/02bSplittingPython/DHX9_WT_rep3_R2_tmp.fastq", "RawData/02bSplittingPython/DHX9_UV_rep1_R2_tmp.fastq", "RawData/02bSplittingPython/DHX9_UV_rep2_R2_tmp.fastq", "RawData/02bSplittingPython/DHX9_UV_rep3_R2_tmp.fastq"], "indir": "RawData/01bFastqTrimBarcode", "tmp2": ["RawData/02bSplittingPython/DHX9_WT_rep1_R2.fastq", "RawData/02bSplittingPython/DHX9_WT_rep2_R2.fastq", "RawData/02bSplittingPython/DHX9_WT_rep3_R2.fastq", "RawData/02bSplittingPython/DHX9_UV_rep1_R2.fastq", "RawData/02bSplittingPython/DHX9_UV_rep2_R2.fastq", "RawData/02bSplittingPython/DHX9_UV_rep3_R2.fastq"], "outdir": "RawData/02bSplittingPython"}, "type": "single", "local": false, "input": ["RawData/01bFastqTrimBarcode/20190410hela_endoDHX9_FLASH_R1.fastq.gz", "RawData/01bFastqTrimBarcode/20190410hela_endoDHX9_FLASH_R2.fastq.gz"], "resources": {}, "jobid": 80, "wildcards": {}, "threads": 20, "output": ["RawData/02bSplittingPython/DHX9_WT_rep1_R1.fastq.gz", "RawData/02bSplittingPython/DHX9_WT_rep2_R1.fastq.gz", "RawData/02bSplittingPython/DHX9_WT_rep3_R1.fastq.gz", "RawData/02bSplittingPython/DHX9_UV_rep1_R1.fastq.gz", "RawData/02bSplittingPython/DHX9_UV_rep2_R1.fastq.gz", "RawData/02bSplittingPython/DHX9_UV_rep3_R1.fastq.gz", "RawData/02bSplittingPython/DHX9_WT_rep1_R2.fastq.gz", "RawData/02bSplittingPython/DHX9_WT_rep2_R2.fastq.gz", "RawData/02bSplittingPython/DHX9_WT_rep3_R2.fastq.gz", "RawData/02bSplittingPython/DHX9_UV_rep1_R2.fastq.gz", "RawData/02bSplittingPython/DHX9_UV_rep2_R2.fastq.gz", "RawData/02bSplittingPython/DHX9_UV_rep3_R2.fastq.gz"], "cluster": {"memory": "6G"}, "rule": "DemultiplexPython"}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv && \
/package/anaconda3/envs/snakemake-5.1.2/bin/python \
-m snakemake RawData/02bSplittingPython/DHX9_WT_rep1_R1.fastq.gz RawData/02bSplittingPython/DHX9_WT_rep2_R1.fastq.gz RawData/02bSplittingPython/DHX9_WT_rep3_R1.fastq.gz RawData/02bSplittingPython/DHX9_UV_rep1_R1.fastq.gz RawData/02bSplittingPython/DHX9_UV_rep2_R1.fastq.gz RawData/02bSplittingPython/DHX9_UV_rep3_R1.fastq.gz RawData/02bSplittingPython/DHX9_WT_rep1_R2.fastq.gz RawData/02bSplittingPython/DHX9_WT_rep2_R2.fastq.gz RawData/02bSplittingPython/DHX9_WT_rep3_R2.fastq.gz RawData/02bSplittingPython/DHX9_UV_rep1_R2.fastq.gz RawData/02bSplittingPython/DHX9_UV_rep2_R2.fastq.gz RawData/02bSplittingPython/DHX9_UV_rep3_R2.fastq.gz RawData/02bSplittingPython/Logs/demultiplex.python.log --snakefile /data/processing3/akhtargroup/sunyd/Snakemake/snakemake-TTseq/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/.snakemake/tmp.q1ui2i25 RawData/01bFastqTrimBarcode/20190410hela_endoDHX9_FLASH_R1.fastq.gz RawData/01bFastqTrimBarcode/20190410hela_endoDHX9_FLASH_R2.fastq.gz --latency-wait 300 \
 --attempt 1 \
--force-use-threads --wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/config.yaml  --nocolor \
--notemp --no-hooks --nolock --timestamp --mode 2  --force-use-threads  --allowed-rules DemultiplexPython  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/.snakemake/tmp.q1ui2i25/80.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/.snakemake/tmp.q1ui2i25/80.jobfailed"; exit 1)

