#!/bin/sh
# properties = {"type": "single", "rule": "StatisticsSecondRscript", "local": false, "input": ["Output/03aStatisticsSTARRscript/DHX9_WT_rep1.txt", "Output/03aStatisticsSTARRscript/DHX9_WT_rep2.txt", "Output/03aStatisticsSTARRscript/DHX9_WT_rep3.txt", "Output/03aStatisticsSTARRscript/DHX9_UV_rep1.txt", "Output/03aStatisticsSTARRscript/DHX9_UV_rep2.txt", "Output/03aStatisticsSTARRscript/DHX9_UV_rep3.txt", "ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_WT_rep1/peaks.bed", "ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_WT_rep2/peaks.bed", "ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_WT_rep3/peaks.bed", "ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_UV_rep1/peaks.bed", "ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_UV_rep2/peaks.bed", "ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_UV_rep3/peaks.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_merged.bed"], "output": ["Output/03aStatisticsSTARRscript/total.read.statistics.txt", "Output/03aStatisticsSTARRscript/total.peaks.statistics.txt"], "wildcards": {}, "params": {"demultiplex_ori": "RawData/02aSplittingRscript/FlexbarOutput.log", "demultiplex": "Output/03aStatisticsSTARRscript/demultiplex.txt", "outdir": "Output/03aStatisticsSTARPython"}, "log": [], "threads": 1, "resources": {}, "jobid": 5, "cluster": {"memory": "30G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv && \
/home/suny/miniconda3/bin/python3.6 \
-m snakemake Output/03aStatisticsSTARRscript/total.read.statistics.txt --snakefile /data/processing3/akhtargroup/sunyd/Snakemake/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/.snakemake/tmp.1zmdsnm8 Output/03aStatisticsSTARRscript/DHX9_WT_rep1.txt Output/03aStatisticsSTARRscript/DHX9_WT_rep2.txt Output/03aStatisticsSTARRscript/DHX9_WT_rep3.txt Output/03aStatisticsSTARRscript/DHX9_UV_rep1.txt Output/03aStatisticsSTARRscript/DHX9_UV_rep2.txt Output/03aStatisticsSTARRscript/DHX9_UV_rep3.txt ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_WT_rep1/peaks.bed ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_WT_rep2/peaks.bed ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_WT_rep3/peaks.bed ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_UV_rep1/peaks.bed ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_UV_rep2/peaks.bed ProcessedData/03bPeakCallingSTARPeakachuRscript/DHX9_UV_rep3/peaks.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_merged.bed --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/FLASH-seq.config.yaml  --nocolor \
--notemp --no-hooks --nolock --mode 2  --allowed-rules StatisticsSecondRscript  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/.snakemake/tmp.1zmdsnm8/5.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuv/.snakemake/tmp.1zmdsnm8/5.jobfailed"; exit 1)

