#!/bin/sh
# properties = {"type": "single", "rule": "PeaksCallingPureclipPython", "local": false, "input": ["ProcessedData/01bRemoveDuplicatesSTARPython/DHX9_UV_rep1.filtered.bam", "ProcessedData/01bRemoveDuplicatesSTARPython/DHX9_UV_rep2.filtered.bam", "ProcessedData/01bRemoveDuplicatesSTARPython/DHX9_UV_rep3.filtered.bam"], "output": ["ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/merged.bam", "ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/merged.bam.bai", "ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/peaks.separated.bed", "ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/peaks.bed", "ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/peaks.params"], "wildcards": {"group": "DHX9_UV"}, "params": {"sampleinfo": "/data/processing3/akhtargroup/sunyd/Projects/FastqZhou2019FlashHumanDHXuv/sampleInfo.tsv", "fold_change": "2.5", "genome_fasta": "/data/repository/organisms/GRCh38_ensembl/genome_fasta/genome.fa", "output_dir": "ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/"}, "log": ["ProcessedData/03bPeakCallingSTARPureclipPython/logs/tss.DHX9_UV.log"], "threads": 20, "resources": {}, "jobid": 153, "cluster": {"memory": "6G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanDHXuvNuclear && \
/data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/bin/python3.7 \
-m snakemake ProcessedData/03bPeakCallingSTARPureclipPython/DHX9_UV/peaks.bed --snakefile /home/suny/scripts/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanDHXuvNuclear/.snakemake/tmp.oc871mix ProcessedData/01bRemoveDuplicatesSTARPython/DHX9_UV_rep1.filtered.bam ProcessedData/01bRemoveDuplicatesSTARPython/DHX9_UV_rep2.filtered.bam ProcessedData/01bRemoveDuplicatesSTARPython/DHX9_UV_rep3.filtered.bam /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/eeac4364 --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanDHXuvNuclear --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanDHXuvNuclear/FLASH-seq.config.yaml  --allowed-rules PeaksCallingPureclipPython --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-conda  --conda-prefix /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanDHXuvNuclear/.snakemake/tmp.oc871mix/153.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanDHXuvNuclear/.snakemake/tmp.oc871mix/153.jobfailed"; exit 1)

