#!/bin/sh
# properties = {"type": "single", "rule": "PeaksAnnotationTSSRscript", "local": false, "input": ["ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed", "ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_merged.bed", "ProcessedData/AnnotationObjects/species.database.constitutive.exons.gtf", "ProcessedData/AnnotationObjects/species.database.constitutive.introns.gtf"], "output": ["Output/05aPeakAnnotationSTARTSSRscript/peaks.annotation.txt"], "wildcards": {}, "params": {"peakdir": "03aPeakCallingSTARTSSRscript", "rscript": "/home/suny/scripts/snakeRNAPipes/shared/tools/FLASH.peak.annotation.R", "alu": "~/sunyd/Genome/RepeatMasker/hg38.repeatmasker.alu.ensembl.bed", "alunot": "~/sunyd/Genome/RepeatMasker/hg38.repeatmasker.alu.not.ensembl.bed", "currentdir": "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs"}, "log": ["Output/05aPeakAnnotationSTARTSSRscript/logs/peak.annotation.log"], "threads": 20, "resources": {}, "jobid": 84, "cluster": {"memory": "6G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs && \
/data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/bin/python3.7 \
-m snakemake Output/05aPeakAnnotationSTARTSSRscript/peaks.annotation.txt --snakefile /home/suny/scripts/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.ugh_q_ye ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_WT.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_DHX9_UV.bed ProcessedData/03aPeakCallingSTARTSSRscript/tss_foldch_2.5_merged.bed ProcessedData/AnnotationObjects/species.database.constitutive.exons.gtf ProcessedData/AnnotationObjects/species.database.constitutive.introns.gtf /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/e124a57d --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/FLASH-seq.config.yaml  --allowed-rules PeaksAnnotationTSSRscript --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-conda  --conda-prefix /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.ugh_q_ye/84.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2019FlashHumanDHXuvCytoFirstPairs/.snakemake/tmp.ugh_q_ye/84.jobfailed"; exit 1)

