#!/bin/sh
# properties = {"type": "single", "rule": "multiQCRscript", "local": false, "input": ["RawData/01aFastqTrimAdapter/fastqc/Cyto-hnRNPM-FLASH_R1_fastqc.html", "RawData/01aFastqTrimAdapter/fastqc/Cyto-hnRNPM-FLASH_R2_fastqc.html", "RawData/01aFastqTrimAdapter/Cyto-hnRNPM-FLASH_R1.fastq.gz", "RawData/01aFastqTrimAdapter/Cyto-hnRNPM-FLASH_R2.fastq.gz", "RawData/03aMappingSTARRscript/DHX9_WT_rep1.bam", "RawData/03aMappingSTARRscript/DHX9_WT_rep2.bam", "RawData/03aMappingSTARRscript/DHX9_WT_rep3.bam", "RawData/03aMappingSTARRscript/DHX9_UV_rep1.bam", "RawData/03aMappingSTARRscript/DHX9_UV_rep2.bam", "RawData/03aMappingSTARRscript/DHX9_UV_rep3.bam"], "output": ["Output/01aMultiqcSTARRscript/multiqc_report.html"], "wildcards": {}, "params": {"indirs": " RawData/01aFastqTrimAdapter/fastqc RawData/01aFastqTrimAdapter RawData/03aMappingSTARRscript", "outdir": "Output/01aMultiqcSTARRscript"}, "log": ["Output/01aMultiqcSTARRscript/multiQC.log"], "threads": 1, "resources": {}, "jobid": 57, "cluster": {"memory": "6G"}}
cd /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto && \
/data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/bin/python3.7 \
-m snakemake Output/01aMultiqcSTARRscript/multiqc_report.html --snakefile /home/suny/scripts/snakeRNAPipes/workflows/FLASH-seq/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/.snakemake/tmp.gs3gfsm6 RawData/01aFastqTrimAdapter/fastqc/Cyto-hnRNPM-FLASH_R1_fastqc.html RawData/01aFastqTrimAdapter/fastqc/Cyto-hnRNPM-FLASH_R2_fastqc.html RawData/01aFastqTrimAdapter/Cyto-hnRNPM-FLASH_R1.fastq.gz RawData/01aFastqTrimAdapter/Cyto-hnRNPM-FLASH_R2.fastq.gz RawData/03aMappingSTARRscript/DHX9_WT_rep1.bam RawData/03aMappingSTARRscript/DHX9_WT_rep2.bam RawData/03aMappingSTARRscript/DHX9_WT_rep3.bam RawData/03aMappingSTARRscript/DHX9_UV_rep1.bam RawData/03aMappingSTARRscript/DHX9_UV_rep2.bam RawData/03aMappingSTARRscript/DHX9_UV_rep3.bam /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes/f1b063b6 --latency-wait 300 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
--directory /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto --configfile /data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/FLASH-seq.config.yaml  --allowed-rules multiQCRscript --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-conda  --conda-prefix /data/processing3/akhtargroup/sunyd/miniconda3/envs/snakeRNAPipes  && touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/.snakemake/tmp.gs3gfsm6/57.jobfinished" || (touch "/data/processing3/akhtargroup/sunyd/Projects/Zhou2020FlashHumanhnRNPMuvCyto/.snakemake/tmp.gs3gfsm6/57.jobfailed"; exit 1)

